## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df = vacation_df.drop(vacation_df.columns[0],axis = 1)
vacation_df.head()

City Country  Max Temp Current Description    Lat     Lng  \
0        Buala      SB     86.16          light rain  -8.14  159.59   
1        Vaini      TO     80.60    scattered clouds -21.20 -175.20   
2         Hilo      US     84.20    scattered clouds  19.73 -155.09   
3    Carnarvon      AU     82.40           clear sky -24.87  113.63   
4  La Asuncion      VE     89.60     overcast clouds  11.03  -63.86   

              Hotel Name  
0   Maringe Lagoon Lodge  
1    Keleti Beach Resort  
2    Hilo Hawaiian Hotel  
3  Hospitality Carnarvon  
4   Colinas de Matasiete

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Jardim De Piranhas")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Jardim De Piranhas")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] =="Olinda")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Touros")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Trairi")]

Jardim_De_Piranhas_df = vacation_df.loc[vacation_df.index == "Jardim De Piranhas"]
Olinda_df = vacation_df.loc[vacation_df.index == "Olinda"]
Touros_df = vacation_df.loc[vacation_df.index == "Touros"]

Trairi_df = vacation_df.loc[vacation_df.index == "Trairi"]

C:\Users\chrer\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexes\base.py:122: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = op(self.values, np.asarray(other))


In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = np.round(vacation_start[["Lat", "Lng"]].to_numpy(),1)
end = np.round(vacation_end[["Lat", "Lng"]].to_numpy(),1)
stop1 = np.round(vacation_stop1[["Lat", "Lng"]].to_numpy(),1)
stop2 = np.round(vacation_stop2[["Lat", "Lng"]].to_numpy(),1)
stop3 = np.round(vacation_stop3[["Lat", "Lng"]].to_numpy(),1)

start,end,stop1,stop2,stop3

(array([[ -6.4, -37.4]]),
 array([[ -6.4, -37.4]]),
 array([[ -8. , -34.9]]),
 array([[ -5.2, -35.5]]),
 array([[ -3.3, -39.3]]))

In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
start_map = -6.4, -37.4
end_map = -6.4, -37.4
stop1_map = -8., -34.9
stop2_map = -5.2, -35.5
stop3_map = -3.3, -39.3

fig = gmaps.figure()
Brazilian_trip = gmaps.directions_layer(start_map, end_map, waypoints=[stop1_map, stop2_map, stop3_map], travel_mode="DRIVING")
fig.add_layer(Brazilian_trip)
fig


Figure(layout=FigureLayout(height='420px'))

In [8]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City Country  Max Temp Current Description   Lat    Lng  \
0  Jardim De Piranhas      BR     80.13    scattered clouds -6.38 -37.35   
1              Olinda      BR     80.60       broken clouds -8.01 -34.86   
2              Touros      BR     80.60    scattered clouds -5.20 -35.46   
3              Trairi      BR     80.37     overcast clouds -3.28 -39.27   

                      Hotel Name  
0                      AP da NIL  
1                   Hotel 5 Sóis  
2                INN NEW HORIZON  
3  Pousada Field Lilies - Trairi

In [9]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [10]:
# 11a. Add a marker layer for each city to the map.
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))